### ISSUE TITLE
python скрипт не отрабатывет 

### ISSUE THREAD

**Issue by muxun** [JustNickSPb/botkin_test#1]
При запуске docker-compose ломается контейнер с питон скриптом 

```
10:54 $ docker logs 37772146dbf5 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 239, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on '0.0.0.0:3306' (111)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//make_changes.py", line 104, in <module>
    mysql = connect(
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 85, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1009, in connect
    self._open_connection()
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 241, in _open_connection
    raise errors.get_mysql_exception(msg=exc.msg, errno=exc.errno,
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '0.0.0.0:3306' (111)
Done
```

В чем может быть проблема и как ее решить?

**Comment by JustNickSPb** [comment]
Согласен. Проверял у себя, как оказалось, без удаления volume'ов, остававшихся после предыдущих запусков, в результате база поднималась достаточно быстро.
Увеличил время ожидания в скрипте, сейчас база должна успевать подняться.
Опубликовал изменения, проверьте, пожалуйста

**Comment by JustNickSPb** [comment]
> Согласен. Проверял у себя, как оказалось, без удаления volume'ов, остававшихся после предыдущих запусков, в результате база поднималась достаточно быстро.
> Увеличил время ожидания в скрипте, сейчас база должна успевать подняться.
> Опубликовал изменения, проверьте, пожалуйста

Прошу прощения, это тоже был костыль, причем работающий не во всех случаях.
Исправил добавлением "restart: always" для контейнера со скриптом.
Заодно, это позволило избавиться от ужасающего костыля в виде time.sleep()  в пайтон-коде.
Изменения опубликованы, проверьте, пожалуйста решение проблемы
